### ISSUE TITLE
Problem with analog stick

### ISSUE THREAD

**Issue by jdrosariop** [wermipls/pj64-wiiu-gcn#10]
Hi. I detected an issue when using the analog stick. If trigger it gently to any direction (like less than half of range) it goes to the right direction. But if go full range either up or right goes to the opposite direction (If I go full up it goes down; if I go full right it goes left). I've tested with Project64 1.6, 2.3 and 3.0 and with plugin 0.2.2 and 0.2.4, always with the same result.

**Comment by wermipls** [comment]
hi! i actually fixed this in commit 606f8e6 but never made a proper release. i just uploaded a v0.2.5 binary release that incorporates the fix : )

**Comment by jdrosariop** [comment]
It works perfect now. Thank you so much. My kids will enjoy this :)
