### ISSUE TITLE
Do something about blocking polling mode

### ISSUE THREAD

**Issue by wermipls** [wermipls/pj64-wiiu-gcn#14]
the adapter receives the state of all four controllers during one poll, while the plugin api only asks for one controller state at a time. assuming a game that polls all 4 controllers every frame, naively polling on every get keys call will make the game slow down at least in half, assuming default adapter bInterval of 8ms.

non-async polling is an awful hack and a leftover from the initial development phase of the plugin. the current behavior is to only poll on the first controller read, but that doesn't work at all if the only controllers polled are in port 2-4.

a better heuristic could be implemented: have a bit field reset after every adapter poll. when controller n gets polled, flip bit n. if bit ends up set, don't poll the adapter. if it's reset, that means we have old data for the given controller and should do another adapter poll.

otherwise, frankly it's literally a problem that threading exists as a solution for. either completely remove it or show a warning that it's not recommended to use

**Comment by FlutterSny** [comment]
Hello Wermipls, and thank you for this driver. it's the best way I found to use my ngc controller on pj64, and works amazingly well for speedrunning.
I'm sorry to send a message here, it's the only way I found to contact you, I'm not familiar with github at all, I hope I'm not upsetting you.
I have a few questions regarding the driver. even though I have no coding experience, I'd like to make this work with an input display, I'm not sure it's possible.
Do you think it's possible, and if so, would you have an idea of how I could make it work?

Thank you, I wish you a nice day.
