### ISSUE TITLE
Plugin Does Not Detect Wavebird Controllers Through Official Switch Adapter

### ISSUE THREAD

**Issue by swoolbean** [wermipls/pj64-wiiu-gcn#4]
Apologies if this is a known "won't fix" sort of issue, but none of my Wavebird controllers are getting detected by the Project64 plugin. I'm using the official Nintendo Switch GameCube adapter, and I've tried multiple genuine Nintendo Wavebirds and receivers, all of which work as expected when playing games in Dolphin using the same adapter.

I'm seeing this behavior with v0.2.3 of the plugin. Not sure if this is an issue with earlier versions, as that's the only one I've tried.

Also, I've made sure that the Wavebirds aren't set to the wrong channels, and the lights on the receivers are lighting up when I send inputs. 

Here's my log file:
[pj64-wiiu-gcn.txt](https://github.com/wermipls/pj64-wiiu-gcn/files/9483412/pj64-wiiu-gcn.txt)

**Comment by wermipls** [comment]
hi, thanks for the report! seems like a problem with the status check, try this version and let me know if it solves the issue

[pj64-wiiu-gcn-1a164e4.zip](https://github.com/wermipls/pj64-wiiu-gcn/files/9483570/pj64-wiiu-gcn-1a164e4.zip)

**Comment by swoolbean** [comment]
Yep, that fixed it! Thanks so much.
