### ISSUE TITLE
Add Z button on gamecube as c-button down

### ISSUE THREAD

**Issue by DTnobi** [wermipls/pj64-wiiu-gcn#6]
please

**Comment by wermipls** [comment]
hi! sorry, but i am not willing to work on this; it's pointless to add a hardcoded configuration for every binding people want. if someone submits a pull request for this, i'll accept it, but i personally would rather work on a proper configuration gui so people can set up arbitrary mappings

**Comment by wermipls** [comment]
i made an issue for the remapping ui (#7) if you want to be up to date on that, however my life is quite busy at the moment so it might take a while before it gets implemented

**Comment by DTnobi** [comment]
yeah, actually that would be better, i'll be patient, thanks
