### ISSUE TITLE
add a proper mapping gui

### ISSUE THREAD

**Issue by wermipls** [wermipls/pj64-wiiu-gcn#7]
let user assign arbitrary binds for each button/analog input; it could be something as simple as having a dropdown for each GC input with corresponding N64 input (probably easiest to implement), or it could be n-rage style, where you click on a n64 button and press desired input on the GameCube controller.

a nice bonus would be if you could set up separate mappings for each controller, as well as automatically import configuration from old versions of the plugin

**Comment by imsl0wer** [comment]
Any updates on this yet?

**Comment by wermipls** [comment]
hi, i've been busy with life and other projects lately, i'll see if i can hack up something usable this week or so :o)

**Comment by wermipls** [comment]
just made a new release with the mapping ui and a couple other stuffs :o) enjoy https://github.com/wermipls/pj64-wiiu-gcn/releases/tag/v1.0.0
